### ISSUE TITLE
scripts/FastCGI.py 第17行报错

### ISSUE THREAD

**Issue by lonycc** [Esonhugh/Gopherus3#1]
如题，第17行代码 `temp1 = chr(len(data) / 256)`，python3 除法取整应该是用`//`，所以应改成 `temp1 = chr(len(data) // 256)`

**Comment by Esonhugh** [comment]
我检查一下

**Comment by Esonhugh** [comment]
fixed at: https://github.com/Esonhugh/Gopherus3/commit/db7d03f47874ad3d79e00df296b4940d2ef94a00
